docs: specify that it should be installed as devDependencies
vercel/style-guide pull request #55
Opened 2023-01-05 14:12 UTC by Divlo

Hello! :wave:

While doing a PR for https://github.com/styfle/links-awakening.
I noticed that in the README, you're recommending to install `@vercel/style-guide` as a normal dependecy, but it should be installed as a `devDependencies`.

This PR updates `README.md` to recommend installing `@vercel/style-guide` as `devDependencies`.

2023-01-24 20:48 UTC, Divlo commented
cc @Styfle, @mrmckeb, @codybrouwers
Friendly ping. :smile:

2023-01-24 21:25 UTC, styfle approved these changes, later dismissed
Thanks!

2023-01-24 21:50 UTC, kayernyc submitted a review, later dismissed
-D and -S for the win!

2023-01-25 01:37 UTC, mrmckeb requested changes
Can you change the commit message to what I've updated the title to please? We auto-generate release notes and try to keep these short. I'll then merge - thank you!

2023-01-25 03:44 UTC, mrmckeb approved these changes

2023-01-25 03:45 UTC, merged

2023-01-25 03:45 UTC, mrmckeb commented
I made that change for you, and have merged - thank you!

2023-08-29 07:28 UTC, mrmckeb commented
:tada: This PR is included in version 5.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@vercel/style-guide/v/5.0.0)
- [GitHub release](https://github.com/vercel/style-guide/releases/tag/v5.0.0)