fix: `es2023` is not valid
vercel/style-guide pull request #84
Opened 2023-12-31 10:01 UTC by mwskwong

According to
- https://www.typescriptlang.org/tsconfig#lib, and
- https://www.typescriptlang.org/tsconfig#target

`es2023` is not a valid value for `lib` and `target`. I propose using `esnext` for now (which is equivalent to `es2023` in a sense) and keep monitoring the status, since once `es2023` is available, `esnext` is likely equivalent to `es2024`.

2024-01-31 21:20 UTC, Ethan-Arrowood approved these changes

2024-01-31 21:21 UTC, Ethan-Arrowood requested changes

2024-01-31 21:21 UTC, Ethan-Arrowood commented on typescript/tsconfig.node18.json
> +    "lib": ["esnext"],
I think lib is fine as is actually. seems to be an allowed value based on tsconfig json schema

2024-01-31 21:21 UTC, Ethan-Arrowood commented on typescript/tsconfig.node20.json
> +    "lib": ["esnext"],
I think lib is fine as is actually. seems to be an allowed value based on tsconfig json schema

2024-01-31 21:22 UTC, Ethan-Arrowood commented
<img width="662" alt="Screenshot 2024-01-31 at 14 22 15" src="https://github.com/vercel/style-guide/assets/16144158/e7b63d70-d6ca-4d43-a89e-62ebafa6c11f">

2024-01-31 21:27 UTC, Ethan-Arrowood commented on typescript/tsconfig.node18.json
> +    "target": "esnext",
```suggestion
    "target": "es2022",
```
this should be 2022 based off of what I'm seeing here: https://github.com/tsconfig/bases/blob/main/bases/node18.json

2024-02-01 01:54 UTC, mwskwong commented
@Ethan-Arrowood Updated accordingly. However, I noticed https://github.com/tsconfig/bases/blob/main/bases/node20.json suggests the `target` for Node 20 should also be `es2022`. See whether you wish to have that aligned as well.

2024-02-01 01:57 UTC, Ethan-Arrowood commented
Oh good point. Yeah I guess so. I think something is off with the timing (Node18 specifically) and it confused me. Thanks for contributing this!

2024-02-01 07:29 UTC, mrmckeb approved these changes

2024-02-01 15:06 UTC, Ethan-Arrowood approved these changes

2024-02-02 01:28 UTC, merged

2024-02-02 01:28 UTC, mrmckeb commented
Thanks for the PR @mwskwong, and for the review @Ethan-Arrowood!